# Site Settings
locale: "en-US"
title: Jeremy Lloyd Conlin
subtitle: My home on the intertubes
# email: jlconlin@me.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website for Jeremy Lloyd Conlin to share my professional activities 
  and a blog of my personal hobbies.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jl.conlin.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jlconlin
github_username:  jlconlin

author_profile: true
markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
  - jekyll/scholar
  - jekyll-archives

# Theme settings
theme: minimal-mistakes-jekyll
repository: "jlconlin/jlconlin.github.io"
search: true
breadcrumbs: true
show_date: true

defaults:
  # _posts
  - scope:
      path: _posts
      type: posts
    values:
      author_profile: true
      layout: single
      comments: true
      permalink: /blog/:year/:month/:day/:title

author:
  # name     : "Jeremy Lloyd Conlin"
  avatar   : "/assets/images/profile.png"
  bio      : "Computational physicist with nuclear engineering and nuclear data experience"
  # email    : "jlconlin@me.com"
  # location : "Los Alamos, NM"
  links    : 
    - label: "Home"
      icon: "fas fas fa-home"
      url: "https://jl.conlin.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jlconlin"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jlconlin"
    - label: "About"
      icon: "fab far fa-address-card"
      url: "https://jl.conlin.io/about"

# Social Sharing
twitter:
  username: &twitter "jlconlin"

# build settings
livereload: true
# port: 4001
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/category/:name/'

scholar:
  source: "_pages/CV"
  sort_by: "year,month"
  order: "descending"
  bibliography: "Bibliography.bib"
  relative: "/CV/Publications.html"
  bibtex_filters:
    - latex

include:
  - _pages
  - assets

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
