title: Jeremy Lloyd Conlin
# email: jlconlin@me.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jl.conlin.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jlconlin
github_username:  jlconlin

author_profile: true
markdown: kramdown

plugins:
  - jekyll/scholar

# Theme settings
theme: minimal-mistakes-jekyll
search: true
breadcrumbs: true
author:
  # name     : "Jeremy Lloyd Conlin"
  avatar   : "/images/profile.png"
  bio      : "Computational physicist with nuclear engineering and nuclear data experience"
  # email    : "jlconlin@me.com"
  # location : "Los Alamos, NM"
  links    : 
    - label: "https://jl.conlin.io"
      icon: "fas fa-fw fa-link"
      url: "https://jl.conlin.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jlconlin"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jlconlin"

# build settings
livereload: true
# port: 4001

scholar:
  source: "_pages/CV"
  bibliography: "Bibliography.bib"
  relative: "/CV/Publications/"

include:
  - _pages
  - _photos

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor
